services:
  - type: web
    name: apidev
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    branch: main
    autoDeploy: true