services:
  - type: web
    name: apidev
    env: python
    buildCommand: |
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apidev-db
          property: connectionString
      - key: DATABASE_HOSTNAME
        fromService:
          name: apidev-db
          type: postgres
          property: host
      - key: DATABASE_NAME
        fromService:
          name: apidev-db
          type: postgres
          property: database
      - key: DATABASE_USERNAME
        fromService:
          name: apidev-db
          type: postgres
          property: user
      - key: DATABASE_PASSWORD
        fromService:
          name: apidev-db
          type: postgres
          property: password

  - type: postgres
    name: apidev-db
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow external connections