services:
  - type: web
    runtime: python
    name: apidev
    region: oregon
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /docs